#spring.application.name=fintrack
#
## ===============================
## DATABASE CONFIG (MySQL)
## ===============================
##spring.datasource.url=jdbc:mysql://localhost:3306/fintrack_db
##spring.datasource.username=root
##spring.datasource.password=root
##spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.datasource.url=jdbc:postgresql://ep-frosty-mountain-aortesgt-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_oMQ7w0NLzZdS
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
## ===============================
## JPA / HIBERNATE
## ===============================
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#
## ===============================
## SERVER CONFIG
## ===============================
#server.port=8080
#
## ===============================
## GEN AI CONFIG (Gemini)
## ===============================
## Get your API key from https://aistudio.google.com/
#spring.ai.google.genai.api-key=AIzaSyDA17xC1v7bcEf11uoqezQ25xyM0dPAg4Y
#spring.ai.google.genai.chat.options.model=gemini-1.5-flash









spring.application.name=fintrack

# ===============================
# DATABASE CONFIG (PostgreSQL - Neon)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-frosty-mountain-aortesgt-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_oMQ7w0NLzZdS
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
# Use PostgreSQL Dialect (Remove the MySQL one!)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER CONFIG
# ===============================
server.port=8080

# ===============================
# GEN AI CONFIG (Gemini)
# ===============================
spring.ai.google.genai.api-key=AIzaSyDA17xC1v7bcEf11uoqezQ25xyM0dPAg4Y
spring.ai.google.genai.chat.options.model=gemini-1.5-flash